### ISSUE TITLE
img

### ISSUE THREAD

**Issue by lilit-nersisyan** [abi-am/it-resources#2]
AS-W_01_launch-client
![AS-W_01_launch-client](https://user-images.githubusercontent.com/7588977/115360777-017ae480-a1d1-11eb-8f95-8c1eb577b371.png)

AS-W_02_new-session
![image](https://user-images.githubusercontent.com/7588977/115360976-30915600-a1d1-11eb-8a94-e2897fbb3c36.png)

AS-W_03_ssh-session
![image](https://user-images.githubusercontent.com/7588977/115361079-4737ad00-a1d1-11eb-8650-78c56484f0f1.png)

AS-W_04_host-address
![image](https://user-images.githubusercontent.com/7588977/115361186-62a2b800-a1d1-11eb-844b-912aa3d8def4.png)

AS-W_05_user-name
![image](https://user-images.githubusercontent.com/7588977/115361232-6f271080-a1d1-11eb-892b-62192cd51a41.png)

AS-W_06_x11
![image](https://user-images.githubusercontent.com/7588977/115361295-8108b380-a1d1-11eb-9643-ff42404cea7d.png)

AS-W_07_private-key
![image](https://user-images.githubusercontent.com/7588977/115361367-91209300-a1d1-11eb-8619-610b8433855f.png)

AS-W_08_session-name
![image](https://user-images.githubusercontent.com/7588977/115361425-a09fdc00-a1d1-11eb-9dfd-2901128e5278.png)

**Comment by antranigv** [comment]
Closing this as it's not recommended to use MobaXterm anymore. All Windows users will be using PowerShell.
